#============================== Network device ================================
packetbeat.interfaces.device: any

#================================== Flows =====================================
packetbeat.flows:
  timeout: 30s
  period: 10s

#========================== Transaction protocols =============================
packetbeat.protocols:
- type: http
  ports: [80, 8080, 5000]
  send_headers: true
  send_all_headers: true

- type: tls
  ports: [443]
  send_certificates: false

#=========================== Monitored processes ==============================
packetbeat.procs:
  enabled: false
  monitored:
    - process: pgsql
      cmdline_grep: postgres

#================================ Processors ===================================
# For example, you can use the following processors to keep the fields that
# contain CPU load percentages, but remove the fields that contain CPU ticks
# values:
processors:
- include_fields:
   fields: ["cpu"]
- drop_fields:
   fields: ["cpu.user", "cpu.system"]
# The following example drops the events that have the HTTP response code 200:
- drop_event:
   when:
      equals:
          http.code: 200
# The following example enriches each event with metadata from the cloud provider about the host machine.
- add_docker_metadata:
   host: "unix:///var/run/docker.sock"
- add_cloud_metadata: ~
- add_locale: ~

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]
  username: elastic
  password: changeme

xpack.monitoring:
  enabled: false
  elasticsearch:

#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index.
# Loading the dashboards is disabled by default and can be enabled either by setting the options here, or by using the `-setup` CLI flag.
setup.dashboards:
  enabled: true
setup.kibana:
  host: "${KIBANA_HOST}:80"
  username: elastic
  password: changeme
